version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend  # Указываем правильный путь
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - STEAM_API_KEY=${STEAM_API_KEY}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend